name: Build and Publish

on: [ push, workflow_dispatch ]

jobs:
    configurator-framer:
        uses: viamedici-spc/github-ci/.github/workflows/build-npm.yml@v2
        with:
            project-dir: 'packages/configurator-framer'
            node-version: '18'
            skip-publish: false
        secrets:
            npm_token: ${{ secrets.NPM_TOKEN }}

    configurator-framer-bundle:
        uses: viamedici-spc/github-ci/.github/workflows/build-npm.yml@v2
        with:
            project-dir: 'packages/configurator-framer-bundle'
            node-version: '18'
            skip-publish: false
        secrets:
            npm_token: ${{ secrets.NPM_TOKEN }}